# Generated by Django 6.0.5 on 2026-06-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_konser', models.CharField(max_length=100)),
                ('artis', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('harga_tiket', models.IntegerField()),
                ('tersedia', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
